<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net6.0;net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<DebugType>portable</DebugType>

		<EnablePackageValidation>true</EnablePackageValidation>
		<PackageValidationBaselineVersion>1.1.0</PackageValidationBaselineVersion>

		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>

		<PackageId>MapFlux</PackageId>
		<Version>1.1.0</Version>
		<Authors>Kadir Demirkaya</Authors>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<Description>A lightweight object-to-object mapping library for .NET with compiled mapping plans, Profile-based and Attribute-based mapping support.</Description>
		<PackageProjectUrl>https://github.com/kadirdemirkaya/MapFlux</PackageProjectUrl>
		<RepositoryUrl>https://github.com/kadirdemirkaya/MapFlux</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>mapper object-mapping mapping dotnet net6 net7 net8 net9 net10</PackageTags>
		<PackageReleaseNotes>Initial release with Profile-based and Attribute-based mapping support.</PackageReleaseNotes>
		<AssemblyInformationalVersion>1.1.0</AssemblyInformationalVersion>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>icon.png</PackageIcon>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\README.md" Pack="true" PackagePath="" />
		<None Include="..\..\LICENSE.txt" Pack="true" PackagePath="" />
		<None Include="..\..\assets\icon.png" Pack="true" PackagePath="" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.111" PrivateAssets="All" />
	</ItemGroup>

</Project>